# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lisi Schauer's Portfolio
email: lisiswebsite@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  good design good design good design
  good design good design good design
baseurl: "/src" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cavedevice
github_username:  lisiswebsite

# Build settings
# theme: minima
plugins:
  - jekyll-feed

include:
  - _pages
  - _redirects

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  comments: []
  endings: []
  #ignore:
    #envs: [local]
  blanklines: false # boolean - strip blank lines and breaks
  profile: false
  startings: []

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
